# Generated by Django 3.2.3 on 2021-06-02 11:03

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('birthdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['title'], 'verbose_name': 'автомобиль', 'verbose_name_plural': 'автомобили'},
        ),
        migrations.AlterModelOptions(
            name='personalitem',
            options={'ordering': ['title'], 'verbose_name': 'личные вещи', 'verbose_name_plural': 'личные вещи'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title'], 'verbose_name': 'услуга', 'verbose_name_plural': 'услуги'},
        ),
    ]
