# Generated by Django 3.2.3 on 2021-06-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210602_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата рождения'),
        ),
    ]
