# Generated by Django 3.2.3 on 2021-05-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210527_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.post')),
                ('color', models.CharField(max_length=20, verbose_name='цвет')),
                ('brand', models.CharField(max_length=20, verbose_name='марка')),
                ('mileage', models.PositiveIntegerField(verbose_name='пробег')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'автомобили',
            },
            bases=('main.post',),
        ),
        migrations.CreateModel(
            name='PersonalItem',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.post')),
                ('condition', models.CharField(choices=[('new', 'новое'), ('used', 'б/у')], default='used', max_length=20, verbose_name='состояние')),
            ],
            options={
                'verbose_name': 'личные вещи',
                'verbose_name_plural': 'личные вещи',
            },
            bases=('main.post',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.post')),
                ('contractor', models.CharField(choices=[('private_person', 'частное лицо'), ('organization', 'организация')], default='private_person', max_length=20, verbose_name='вид исполнителя')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
            bases=('main.post',),
        ),
        migrations.CreateModel(
            name='ArchivedPost',
            fields=[
            ],
            options={
                'verbose_name': 'архивное объявление',
                'verbose_name_plural': 'архивные объявления',
                'ordering': ['created'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.post',),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_categories_posts', to='main.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_sellers_posts', to='main.person', verbose_name='продавец'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='post_posts', to='main.Tag', verbose_name='Теги'),
        ),
    ]
