# Generated by Django 3.2.3 on 2021-06-09 20:37

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', sorl.thumbnail.fields.ImageField(blank=True, upload_to='images')),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
    ]
